title: LiquidJS
subtitle: "A simple, expressive and safe template engine."
description: "LiquidJS is a simple, expressive and safe Shopify / GitHub Pages compatible template engine in pure JavaScript."
author: Harttle
language:
  - en
  - zh-cn
timezone: UTC

url: https://liquidjs.com
root: /
permalink: news/:year/:month/:day/:title/
relative_link: true
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy
skip_render: "api/**"
ignore: "api/**"
include: "api/**"
syntax_highlighter: prismjs
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""

algolia:
  applicationID: QJ35YOZTU4
  apiKey: 8c6cbb824b4c5023f0bb2ef29e228bef
  indexName: liquidjs
twitter: harttleharttle
github: harttle/liquidjs
oc: liquidjs
